export const baseRoutes = {
    auth: "/api/auth",
    profile: "/api/profile",
    user: "/api/user",
    image: "/api/image",
    post: "/api/post",
    posts: "/api/posts",
    comment: "/api/comment",
    chatting: "/api/chatting",
    search: "/api/search",
    friends: "/api/friends",
};

export const routes = {
    auth: {
        login: "/login",
        logout: "/logout",
        join: "/join",
        find: "/find",
        code: "/code",
        modify: "/modify",
        refresh: "/refresh",
    },
    user: {
        detail: "/",
        posts: "/posts/",
        images: "/images/",
        info: "/info/",
    },
    profile: {
        login_info: "/login_info",
        profile: "/profile",
        coverimage: "/coverimage",
        profileimage: "/profileimage",
        introduce: "/introduce",
        people: "/people",
        ability: "/ability",
        university: "/university",
        school: "/school",
    },
    image: {
        single: "/",
        array: "/array",
        remove: "/",
        latest: "/latest",
        all: "/all",
    },
    post: {
        write: "/",
        modify: "/",
        get: "/",
        remove: "/",
        like: "/like",
    },
    posts: {
        all: "/",
        like: "/like",
        bookmark: "/bookmark",
        my: "/my",
        user: "/user",
    },
    comment: {
        get: "/",
        write: "/",
        modify: "/",
        delete: "/",
    },
    search: {
        all: "/all",
        post: "/post",
        people: "/people",
        friend: "/friend",
    },
    friend: {
        is_friend: "/is_friend",
        request: "/request",
        response: "/response",
        request_list: "/request_list",
        response_list: "/response_list",
        friend_list: "/friend_list",
        refuse: "/refuse",
        all: "/all",
    },
};

export const entities: string = "src/entity/*.ts";
