import auth from "./auth";
import chat from "./chat";
import comment from "./comment";
import friends from "./friends";
import post from "./post";
import posts from "./posts";
import search from "./search";
import profile from "./profile";
import user from "./user";
import image from "./image";

export const authApi = auth;
export const chatApi = chat;
export const commentApi = comment;
export const friendsApi = friends;
export const postApi = post;
export const postsApi = posts;
export const searchApi = search;
export const profileApi = profile;
export const userApi = user;
export const imageApi = image;
